jobs:
  - name: data-cleaning
    stages:
      - name: "clean-housing-table"
        tasks:
          - name: "housingds"
            params: {}
          
      - name: "train-test-split"
        tasks:
          - name: "train-test"
            params:
              target: "median_house_value"
              test_size: 0.2

  - name: feat-engg
    stages:
      - name: "feature-pipelines"
        tasks:
          - name: "transform-features"
            params: {}
              
  - name: model-gen
    stages:
      - name: "model-creation"
        tasks:
          - name: "train-model"
            params: {}
              

  - name: model-eval
    stages:
      - name: "model-predict"
        tasks:
          - name: "score-model"
            params: {}
